name: Build macos dmg
on:
  workflow_dispatch:
jobs:
  build:
    name: macos-arm
    runs-on: macos-14
    permissions:
      contents: write
      packages: write
    steps:
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests --user
      - name: Install dependencies
        run: |
          npm install -g asar webpack webpack-cli
          npm install webpack --save-dev
      - name: Show Directory
        run: |
          pwd
          ls -la
